### ISSUE TITLE
Logarithmic and semilog plotting using ManagedWindow

### ISSUE THREAD

**Issue by Laogeodritt** [ralph-group/pymeasure#120]
Is there presently any way of showing log-log or semi-log plots using ManagedWindow? Looks like [pyqtgraph supports it](http://www.pyqtgraph.org/documentation/graphicsItems/plotitem.html#pyqtgraph.PlotItem.setLogMode) but I'm not seeing those facilities called in PyMeasure at the moment.

Main use case for this would be for multi-decade frequency sweeps (x-axis) and plotting power data logarithmically when we're obtaining linear units from an instrument.

**Comment by cjermain** [comment]
@Laogeodritt, great question! I believe that you can right click on the plot to open up the pyqtgraph menu. There should be an option to adjust the plot and axes. If not, PR is certainly welcome.

**Comment by Laogeodritt** [comment]
Yes, that does work! Thanks, I didn't realise there was a context menu.

Do you know if there's any API support for setting these programmatically in PyMeasure right now? I can see that pyqtgraph does but I don't think the possibility is forwarded to the PyMeasure GUI.

If not, maybe something I can work on later. Since we're talking experiment-specific GUIs and automation, having the display automatically configured would certainly be a useful feature.

**Comment by cjermain** [comment]
I'm glad that works. You can certainly adjust the plot programmatically. I would suggest checking out [curves.py](https://github.com/ralph-group/pymeasure/blob/master/pymeasure/display/curves.py) and the pyqtgraph docs. I certainly welcome enhancing the PyMeasure support for different axes.
