### ISSUE TITLE
PyMeasure logo

### ISSUE THREAD

**Issue by cjermain** [ralph-group/pymeasure#15]
For fun, below are 2 possible logos for PyMeasure. @grahamrow, @ndr37, @minhhaiphys, @guenp, any preferences or other suggestions?

1. ![logo](https://cloud.githubusercontent.com/assets/4521567/12904509/f3d65780-ce9d-11e5-98ae-156bcd9de0ff.png)

2. ![pymeasure tmp](https://cloud.githubusercontent.com/assets/4521567/12904602/74eefad4-ce9e-11e5-959e-97d3119e71e1.png)

**Comment by cjermain** [comment]
Ok. @guenp, I've brushed up your original snake-axes design. Any thoughts? I can send you the SVG.

![pymeasure_alt3](https://cloud.githubusercontent.com/assets/4521567/14230046/b395ff42-f916-11e5-810a-293c36d8fa62.png)

**Comment by guenp** [comment]
@cjermain cool, that looks much more a snake and not a worm :stuck_out_tongue_winking_eye:  I think it's perfect! :+1: 
Font-wise, sans-serif is all the rage these days.. I think it looks a bit more slick & works well with the vector art. how's this for example? (I used Questa sans (from fontspring.com) and adjusted the y a bit cause that one looked weird)
<img width="350" alt="screen shot 2016-04-03 at 20 45 14" src="https://cloud.githubusercontent.com/assets/4041805/14234195/fdb58f72-f9dc-11e5-9195-c6a13306c947.png">

**Comment by cjermain** [comment]
Good suggestion on the font type @guenp! I found [Roboto](https://www.google.com/fonts/specimen/Roboto), on [Google Fonts](https://www.google.com/fonts/), which I think has a similar look to Questa sans (I noticed this was made by a Dutch designer). I added some background color and shadow to make the snake more lively. How is this?     

![pymeasure_alt3](https://cloud.githubusercontent.com/assets/4521567/14236955/238bcece-f9eb-11e5-9424-aefb90924416.png)

**Comment by guenp** [comment]
@cjermain Nice! :+1: It's really getting there. Yay Dutch font designers, that is funny. Personally I like the font a little more condensed, like this one: https://www.google.com/fonts/specimen/Source+Sans+Pro
Also, I like the backdrop, very logo-esque. I think the colors need to be more balanced, maybe it needs some pale blue? or a gradient?
<img width="278" alt="screen shot 2016-04-04 at 13 46 03" src="https://cloud.githubusercontent.com/assets/4041805/14247045/9e7d1932-fa6b-11e5-9ac8-cda7c49190c4.png">

**Comment by cjermain** [comment]
Ok. I've switched to Source Sans Pro. I think a solid color looks more modern. I agree the green was too strong, but I perfer (c) on this list. Any preferences?

a) ![pymeasure_alt3](https://cloud.githubusercontent.com/assets/4521567/14247577/fc87d96a-fa3c-11e5-8389-91b3b18d3c11.png)
b) ![pymeasure_alt3](https://cloud.githubusercontent.com/assets/4521567/14247590/269a822a-fa3d-11e5-8c65-2ca540c6b250.png)
c) ![pymeasure_alt3](https://cloud.githubusercontent.com/assets/4521567/14247642/8eb9e0bc-fa3d-11e5-8f87-115092b290bf.png)
d) ![pymeasure_alt3](https://cloud.githubusercontent.com/assets/4521567/14247863/21aac304-fa3f-11e5-8634-42ab5930bb19.png)

**Comment by guenp** [comment]
Ok, that looks much better! I would make the graph snake just a little bit smaller compared to the text and move it a few pixels to the left. :smile: @ndr37 @minhhaiphys @mhdg @grahamrow what do you guys think?
<img width="180" alt="screen shot 2016-04-05 at 13 43 44" src="https://cloud.githubusercontent.com/assets/4041805/14280676/7a5a5c80-fb34-11e5-967a-3afb6067f8ad.png">

**Comment by minhhaiphys** [comment]
Thanks for the nice work! That looks good to  me.

**Comment by cjermain** [comment]
Thanks everyone for the feedback. The new logo is live.
