### ISSUE TITLE
Example iv_keithley.py gives Error

### ISSUE THREAD

**Issue by JH0894** [ralph-group/pymeasure#216]
Hey everyone,

I'm new to PyMeasure and I am trying around a bit with the examples to get a feel for how it works. I tried to run the iv_keithley.py example that I found here on GitHub with a Keithley that I have. I changed the GPIB address and changed the directory. When I run the file, the window shows up. However, when I click on "queue" it gives this error (see picture). Does anyone know how to solve this? Thanks in advance!

![error](https://user-images.githubusercontent.com/53299376/61867652-fa2d8680-aed7-11e9-823f-2d77b546c189.png)

**Comment by jmittelstaedt** [comment]
Hi,

I believe this is the same error as #168.

Some hotfixes were suggested in that thread.

**Comment by bilderbuchi** [comment]
Yes, this is #168, please track that issue instead.
