### ISSUE TITLE
PyVISA keyword `delay` replaced by `query_delay`

### ISSUE THREAD

**Issue by bilderbuchi** [ralph-group/pymeasure#272]
So, since pyVISA 1.6 (quite some time ago), it seems that the `delay` kwarg needs to be replaced by `query_delay` - I think we just missed that.
https://pyvisa.readthedocs.io/en/latest/faq/migrating.html#removal-of-instrument-delay-and-added-instrument-query-delay
As we [still have](https://github.com/ralph-group/pymeasure/blob/e48f9d679d6ee970e2e875d2fc9a5679378b07aa/pymeasure/adapters/visa.py#L59) the `delay` defined as safe, we should change that to `query_delay`.
The only other place that I found (with Github) where we used that is [in an Agilent device](https://github.com/ralph-group/pymeasure/blob/07cf309b8d113931525c8cc216cc704f2b7ff413/pymeasure/instruments/agilent/agilent8257D.py#L248).
@cjermain is this something where we need to keep API consistency with other adapters beside the VISAAdapter, or do we just change those two spots and be done? I think the latter, just want to make sure.

**Comment by cjermain** [comment]
Thanks for raising this @bilderbuchi. I agree that it is reasonable to replace the `delay` field with `query_delay`. It's not clear to me if the Agilent case requires the write delay, so `query_delay` is likely a good replacement. If that need does arise, we could always implement it with `time.sleep` in the adapter.
