### ISSUE TITLE
stop_power is mislabeled in agilent8257D.py

### ISSUE THREAD

**Issue by axs5489** [ralph-group/pymeasure#286]
There are two start_power definitions (lines 74 & 80 respectively) in /pymeasure/pymeasure/instruments/agilent/agilent8257D.py

Second start_power (line 80) should actually be stop_power

**Comment by bilderbuchi** [comment]
Indeed, good catch! Would you submit a PR with the fix? https://pymeasure.readthedocs.io/en/latest/dev/contribute.html

**Comment by axs5489** [comment]
Took my a while to figure it out as a hardware engineer barely out of college with no experience in team-based software development,
https://github.com/ralph-group/pymeasure/pull/287

**Comment by bilderbuchi** [comment]
you did great, thanks!
