### ISSUE TITLE
visa.py: How to get binary values without data format.

### ISSUE THREAD

**Issue by Harvey1024** [ralph-group/pymeasure#289]
``` visa.py``` function: ```binary_values()```, return  ```np.fromstring()``` after getting binary string,  
How to just return binary string without data format?  

The binary string read from the instrument is like this:  
```python
import pyvisa
rm=pyvisa.ResourceManager()
res = rm.open_resource('ASRLCOM8::INSTR')
res.write(":KEY TEST")
print( res.read_raw())
# b'X COND A01*A02 >25.0\xea\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\n'  
```

**Comment by bilderbuchi** [comment]
Does the PyVISA [query_binary_values](https://pyvisa.readthedocs.io/en/latest/introduction/rvalues.html#reading-binary-values) method help you? You should be able to access that using `myinstrument.adapter.connection.query_binary_values(args..)`.

**Comment by Harvey1024** [comment]
Thanks, it works.
