### ISSUE TITLE
Remove Python 3.5 support

### ISSUE THREAD

**Issue by bilderbuchi** [ralph-group/pymeasure#338]
Python 3.5 has reached [end-of-life](https://www.python.org/downloads/release/python-3510/) a month ago. It would be awesome to be able to use 3.6 features like [f-strings](https://docs.python.org/3.6/whatsnew/3.6.html#pep-498-formatted-string-literals) in our codebase. People are actually using this in PRs that get submitted (e.g. #324). 
I propose removing 3.5 support. @cjermain @CasperSchippers thoughts?

**Comment by CasperSchippers** [comment]
I would agree that dropping support for 3.5 would be fine now it has reached end-of-life.
