### ISSUE TITLE
LakeShore331 typo

### ISSUE THREAD

**Issue by mhdg** [ralph-group/pymeasure#43]
I found a typo on lakeshore331.py

In line 32, where it reads: "        super(Lakeshore331, self).__init__("
The 's' in Lakeshore should be capital (LakeShore)

**Comment by cjermain** [comment]
Thanks @mhdg for pointing this out. I've started a pull-request (#44)  that fixes this issue and adds the temperature properties we discussed. What other features would be useful for this instrument?

**Comment by cjermain** [comment]
Solve in #44.
