### ISSUE TITLE
Missing dependency on pycomedi

### ISSUE THREAD

**Issue by ghisvail** [ralph-group/pymeasure#78]
Neither the `setuptools` metadata nor the requirements file mention a dependency on `pycomedi`, although the latter is imported in `pymeasure/instruments/comedi.py`. The Sphinx documentation generator is complaining of its absence:
```
/<<PKGBUILDDIR>>/docs/api/instruments/comedi.rst:7: WARNING: autodoc: failed to import module 'pymeasure.instruments.comedi'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc.py", line 529, in import_object
    __import__(self.modname)
  File "/<<PKGBUILDDIR>>/pymeasure/instruments/comedi.py", line 27, in <module>
    from pycomedi.subdevice import StreamingSubdevice
ImportError: No module named 'pycomedi'
```

**Comment by cjermain** [comment]
Good eye @ghisvail! The `pycomedi` library is Linux specific, so it should not be required. How about wrapping the import with a try-catch statement?

**Comment by ghisvail** [comment]
> wrapping the import with a try-catch statement

Indeed, plus giving some meaningful error message describing why the import failed, i.e. either because the platform is not Linux or because `pycomedi` is missing.

**Comment by feinsteinben** [comment]
it can be added as an optional ('extra') requirement in the setup.py file.
http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by bilderbuchi** [comment]
The import guard has been added in b0f08f9c.
