### ISSUE TITLE
Spurious cache files in sdist

### ISSUE THREAD

**Issue by ghisvail** [ralph-group/pymeasure#83]
Please make sure you generate future source tarballs from a **clean** tree. The current tarball (version `0.4.4`) is riddled with cache files that should not be present. Please consider merging #82 followed by a new upload. Thanks.

**Comment by cjermain** [comment]
I added exclusions to `MANIFEST.in` in 4a0e09a3fcc6f540ae74a254f78cce8401bc1d2b to prevent cache files from ending up in the future tarballs. I will cut a new release after merging #85, #86, #87.

**Comment by bilderbuchi** [comment]
This has been fixed in the meantime.
